// GENERATED by scripts/sync-horo-prompts.mjs from prompts/0*.md — do not edit
// by hand. Edit the .md stage file and re-run the script; commit both together.
//
// One atomic request per stage (KAN-204): the notebook is consumed per message,
// so every stage is its own attach + typed-path round trip, and each section
// grounds or fails on its own. The prompts/*.md commentary carries the measured
// evidence for the split; the guardrail contract asserted below is documented
// in prompts/README.md ("The shared guardrail block").

export const HORO_STAGE_IDS = [
  "birth-chart",
  "base-fortune",
  "turning-points",
  "forecast",
  "additional-insights"
];

export const HORO_STAGE_HEADINGS = {
  "birth-chart": "แผนภูมิกำเนิด (Birth Chart)",
  "base-fortune": "ดวงพื้นฐาน (Base Fortune)",
  "turning-points": "จุดเปลี่ยน (Turning Points)",
  "forecast": "พยากรณ์อนาคต (Future Forecast)",
  "additional-insights": "ข้อควรระวัง (Additional Insights)"
};

// Verbatim prompt bodies from prompts/0*.md. {{PLACEHOLDER}} tokens are
// interpolated by buildHoroStagePrompt().
export const HORO_STAGE_TEMPLATES = {
  "birth-chart": {
    heading: "แผนภูมิกำเนิด (Birth Chart)",
    template: "ตรวจสอบด้วยวิธีการของคุณเท่านั้น ไม่ใช้ความรู้ทั่วไป\n\n{{NAME}} เกิด {{BIRTH_DATE}} เวลา {{BIRTH_TIME}} ที่ {{BIRTH_PLACE}}\n(ลองจิ๋ม {{LONGITUDE}}°E)\n\nข้อมูลนี้คำนวณจากระบบ deterministic ของ backend แล้ว:\n{{BIRTH_CONTEXT}}\n\nจงตอบตามลำดับนี้:\n1. สี่เสาปีเกิด-เดือน-วัน-ชั่วโมง พร้อมอธิบายว่าแต่ละเสาบอกอะไร\n2. อำนาจของ Day Master (ตัวแทนของตัวเอง) แข็งหรืออ่อน เพราะอะไร\n3. สัดส่วนธาตุทั้งห้า และธาตุที่ควรใช้/ควรเลี่ยง\n4. ถ้ามีระบบอื่นนอกเหนือจาก BaZi ที่อยู่ใน Notebook ให้ยกมาเพิ่ม — ถ้าไม่มี\n   ก็บอกตรงๆ ว่าไม่มี อย่าเดา\n\nตอบโดยขึ้นต้นด้วยหัวข้อ `## แผนภูมิกำเนิด (Birth Chart)` เพื่อให้ประกอบเป็นเอกสารเดียวได้\nอ้างอิงแหล่งที่มาใน Notebook ทุกประเด็น\nตอบเป็นภาษาไทย"
  },
  "base-fortune": {
    heading: "ดวงพื้นฐาน (Base Fortune)",
    template: "ตรวจสอบด้วยวิธีการของคุณเท่านั้น ไม่ใช้ความรู้ทั่วไป\n\n{{NAME}} เกิด {{BIRTH_DATE}} เวลา {{BIRTH_TIME}} ที่ {{BIRTH_PLACE}}\n(ลองจิ๋ม {{LONGITUDE}}°E)\n\nข้อมูลนี้คำนวณจากระบบ deterministic ของ backend แล้ว:\n{{BIRTH_CONTEXT}}\n\nจงอ่านแนวโน้มชีวิตโดยรวมของ {{NAME}} ในหัวข้อเหล่านี้ทีละหัวข้อ\n1. เส้นทางชีวิตโดยรวม — รูปแบบที่ชีวิตจะเป็นไปอย่างไร\n2. ความรักและความสัมพันธ์\n3. อาชีพและการทำงาน\n4. ทักษะและจุดแข็งที่ควรพัฒนา\n5. ความมั่งคั่งและการเงิน\n\nแต่ละหัวข้อให้เหตุผลจากดวงที่อ้างอิงได้ ไม่ใช่คำทำนายลอยๆ\nถ้าข้อมูลใน Notebook ไม่พอจะอ่านหัวข้อด้านใด ให้บอกตรงๆ ว่าไม่มี\nอย่าเติมสิ่งที่ไม่มีใน Notebook\n\nตอบโดยขึ้นต้นด้วยหัวข้อ `## ดวงพื้นฐาน (Base Fortune)` เพื่อให้ประกอบเป็นเอกสารเดียวได้\nอ้างอิงแหล่งที่มาใน Notebook ทุกประเด็น\nตอบเป็นภาษาไทย"
  },
  "turning-points": {
    heading: "จุดเปลี่ยน (Turning Points)",
    template: "ตรวจสอบด้วยวิธีการของคุณเท่านั้น ไม่ใช้ความรู้ทั่วไป\n\n{{NAME}} เกิด {{BIRTH_DATE}} เวลา {{BIRTH_TIME}} ที่ {{BIRTH_PLACE}}\n(ลองจิ๋ม {{LONGITUDE}}°E)\n\nข้อมูลนี้คำนวณจากระบบ deterministic ของ backend แล้ว:\n{{BIRTH_CONTEXT}}\n\nจงระบุจุดเปลี่ยนสำคัญของชีวิต {{NAME}} เรียงตามอายุ 5–8 จุด\nจากอายุน้อยไปมาก ถ้า Notebook มีเนื้อหารองรับน้อยกว่านั้น ให้ใส่เท่าที่มี\nอย่าเติมจุดที่ไม่มีกลไกในดวงรองรับ\n\nสำหรับแต่ละจุด ระบุ:\n- อายุที่จะเกิดขึ้น (ปี พ.ศ. — พ.ศ. คือ ค.ศ. + 543 จงคำนวณจากปีเกิดที่ให้)\n- เหตุการณ์รูปธรรมว่าจะเป็นอย่างไร\n- กลไกทางดวงที่ทำให้เกิดขึ้น — เช่น การเปลี่ยนแปลงปีนักษา หรือการรวมตัว\n  ของธาตุ อธิบายกลไก ไม่ใช่แค่บอกว่าจะเกิดอะไรขึ้น\n\nถ้าข้อมูลใน Notebook ไม่พอจะชี้จุดเปลี่ยนด้านใด ให้บอกตรงๆ ว่าไม่มี\nอย่าเติมสิ่งที่ไม่มีใน Notebook\n\nตอบโดยขึ้นต้นด้วยหัวข้อ `## จุดเปลี่ยน (Turning Points)` เพื่อให้ประกอบเป็นเอกสารเดียวได้\nอ้างอิงแหล่งที่มาใน Notebook ทุกประเด็น\nตอบเป็นภาษาไทย"
  },
  "forecast": {
    heading: "พยากรณ์อนาคต (Future Forecast)",
    template: "ตรวจสอบด้วยวิธีการของคุณเท่านั้น ไม่ใช้ความรู้ทั่วไป\n\n{{NAME}} เกิด {{BIRTH_DATE}} เวลา {{BIRTH_TIME}} ที่ {{BIRTH_PLACE}}\n(ลองจิ๋ม {{LONGITUDE}}°E)\n\nข้อมูลนี้คำนวณจากระบบ deterministic ของ backend แล้ว:\n{{BIRTH_CONTEXT}}\n\nจงพยากรณ์ช่วงปี {{FROM_YEAR}}–{{TO_YEAR}} ปีละปี\n\nแต่ละปี ระบุ:\n- ธีมหลักของปีนั้นจากดวง\n- เหตุการณ์สำคัญที่คาดว่าจะเกิด และช่วงเวลาในปี\n- ความเสี่ยงที่ควรระวัง\n- กลไกทางดวงที่สนับสนุนคำพยากรณ์นั้น\n\nถ้าข้อมูลใน Notebook ไม่พอจะพยากรณ์ปีด้านใด ให้บอกตรงๆ ว่าไม่มี\nอย่าเติมสิ่งที่ไม่มีใน Notebook\n\nตอบโดยขึ้นต้นด้วยหัวข้อ `## พยากรณ์อนาคต (Future Forecast)` เพื่อให้ประกอบเป็นเอกสารเดียวได้\nอ้างอิงแหล่งที่มาใน Notebook ทุกประเด็น\nตอบเป็นภาษาไทย"
  },
  "additional-insights": {
    heading: "ข้อควรระวัง (Additional Insights)",
    template: "ตรวจสอบด้วยวิธีการของคุณเท่านั้น ไม่ใช้ความรู้ทั่วไป\n\n{{NAME}} เกิด {{BIRTH_DATE}} เวลา {{BIRTH_TIME}} ที่ {{BIRTH_PLACE}}\n(ลองจิ๋ม {{LONGITUDE}}°E)\n\nข้อมูลนี้คำนวณจากระบบ deterministic ของ backend แล้ว:\n{{BIRTH_CONTEXT}}\n\nจงชี้เฉพาะประเด็นที่สำคัญหรือเป็นคำเตือนสำหรับ {{NAME}} 5–7 ประเด็น\nเรียงตามความสำคัญจากมากไปน้อย ถ้ามีน้อยกว่านั้นให้ใส่เท่าที่อ้างอิงได้\n\nแต่ละประเด็น ระบุ:\n- เรื่องที่ต้องระวัง\n- เพราะอะไร — ต้องผูกกับเสาหรือธาตุในดวงเสมอ\n- สิ่งที่ควรทำต่อ\n\nถ้าข้อมูลใน Notebook ไม่พอจะชี้ประเด็นด้านใด ให้บอกตรงๆ ว่าไม่มี\nอย่าเติมสิ่งที่ไม่มีใน Notebook\n\nตอบโดยขึ้นต้นด้วยหัวข้อ `## ข้อควรระวัง (Additional Insights)` เพื่อให้ประกอบเป็นเอกสารเดียวได้\nอ้างอิงแหล่งที่มาใน Notebook ทุกประเด็น\nตอบเป็นภาษาไทย"
  }
};

// Guardrail markers every stage template must carry. Documented in
// prompts/README.md; asserted at build time so a prompt edit that silently
// drops a clause fails loudly here instead of degrading grounding in
// production.
const GUARDRAIL_MARKERS = [
  "ตรวจสอบด้วยวิธีการของคุณเท่านั้น ไม่ใช้ความรู้ทั่วไป", // method-only opener
  "บอกตรงๆ ว่าไม่มี", // honesty clause
  "อ้างอิงแหล่งที่มาใน Notebook ทุกประเด็น", // citation clause
  "ตอบเป็นภาษาไทย" // language clause
];

function assertGuardrails(stageId, template) {
  for (const marker of GUARDRAIL_MARKERS) {
    if (!template.includes(marker)) {
      throw new Error(`Stage '${stageId}' prompt lost the guardrail clause: ${marker}`);
    }
  }
}

for (const stageId of HORO_STAGE_IDS) {
  assertGuardrails(stageId, HORO_STAGE_TEMPLATES[stageId].template);
}

/**
 * Interpolate {{PLACEHOLDER}} tokens for one stage.
 *
 * Missing optional placeholders stay visible as the raw token rather than
 * "undefined": a prompt that silently reads "{{FROM_YEAR}}" pasted into Gemini
 * is recoverable at a glance, an "undefined" year is not.
 *
 * @param {string} stageId one of HORO_STAGE_IDS
 * @param {Record<string, string|number>} params placeholder values
 * @returns {string} the prompt to type into the Gemini tab
 */
export function buildHoroStagePrompt(stageId, params = {}) {
  const stage = HORO_STAGE_TEMPLATES[stageId];
  if (!stage) throw new Error(`Unknown horo stage '${stageId}'`);
  return stage.template.replace(/\{\{([A-Z_]+)\}\}/g, (token, key) => {
    const value = params[key];
    if (value === undefined || value === null || String(value).trim() === "") return token;
    return String(value);
  });
}

/**
 * Assemble the five grounded stage answers into the TEMPLATE.md document.
 * Concatenation is literal: title, then the five answers in stage order —
 * each already opens with its own fixed ## heading.
 */
export function assembleHoroReading(title, stageOutputs) {
  const parts = ["# " + title, ""];
  for (const stageId of HORO_STAGE_IDS) {
    const output = stageOutputs[stageId];
    if (!output || !output.text) continue;
    parts.push(output.text.trim(), "");
  }
  return parts.join("\n").trim();
}
